# Generated by Django 2.2.6 on 2019-10-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sooyusil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('longt', models.FloatField()),
                ('langt', models.FloatField()),
                ('call', models.CharField(max_length=100)),
            ],
        ),
    ]
