# Generated by Django 2.2.6 on 2019-10-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sooyusil', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sooyusil',
            name='langt',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sooyusil',
            name='longt',
            field=models.CharField(max_length=100),
        ),
    ]
